FROM allennlp/allennlp:latest
COPY . /app
WORKDIR /app
RUN pip install allennlp==1.1.0rc2
RUN pip install --pre allennlp-models==1.1.0rc2.dev20200722
RUN pip install -e /app
ENTRYPOINT ["python", "/app/schemata/parse/biaffine/run_parser.py"]
CMD ["data/pp1.asc"]
