FROM python:3.7
COPY . /app
WORKDIR /app
RUN pip install tensorflow==1.15.0
RUN pip install bllipparser==2016.9.11
RUN pip install -e /app
ENTRYPOINT ["python", "/app/schemata/parse/bllip/run_parser.py"]
CMD ["data/pp1.asc"]
