FROM python:3.7
COPY . /app
WORKDIR /app
RUN apt update; apt install default-jre
RUN pip install nltk==3.4.5
RUN pip install -e /app
ENTRYPOINT ["python", "/app/schemata/parse/maltparser/run_parser.py"]
CMD ["data/pp1.asc"]
